apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source: #sync this repo
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: #sync it with this clusterd
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      selfHeal: true
      prune: true